In [1]:
from __future__ import division
import numpy
import pandas

In [2]:
data = pandas.read_csv('yelp_feature.csv')
data.head()

average_stars  elite_count  review_count  business_average_stars     stars
0           4.03            3            95                3.857143  4.000000
1           3.63            0            33                3.976190  3.666667
2           3.71            0            16                3.794118  3.705882
3           4.85            0            17                4.000000  5.000000
4           4.08            4           361                4.076923  4.692308

In [3]:
x = data.drop(['stars'], axis=1)
y = data['stars']
x = numpy.array(x)
y = numpy.rint(numpy.array(y))
print('shape of X {}; shape of Y {}'.format(x.shape, y.shape))

shape of X (1048575, 4); shape of Y (1048575,)


In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2);

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

In [9]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(
    multi_class='multinomial', 
    class_weight={1:0.125, 2:0.125, 3:0.25, 4:0.25, 5:0.25},
    C=1e5, 
    solver='newton-cg'
)
lr.fit(x_train, y_train)

print('The average accuracy of training set is：%s' % lr.score(x_train, y_train))
print('The average accuracy of testing set is：%s' % lr.score(x_test, y_test))
print('Coefficients:\n ', lr.coef_)         # coefficient
print('Constant value:\n ', lr.intercept_)  # constant

The average accuracy of training set is：0.620898600481606
The average accuracy of testing set is：0.6205421643659251
Coefficients:
  [[-2.42418498e+00  6.87681188e-02 -4.36206834e-03 -1.70494459e+00]
 [-1.68748898e+00 -3.50089297e-02  7.14509871e-04 -9.46585119e-01]
 [-5.66078930e-01 -2.32293798e-02  2.88892089e-03 -2.04118024e-01]
 [ 1.40902752e+00  2.06497315e-02  3.11115601e-03  8.76776193e-01]
 [ 3.26872538e+00 -3.11795409e-02 -2.35251843e-03  1.97887154e+00]]
Constant value:
  [ 13.01429863   8.46031829   3.76880838  -6.65568108 -18.58774423]


In [14]:
result=lr.predict(x_test)
cnt = 0
for i in range(len(result)):
    if result[i] != y_test[i]:
        cnt += 1
print(len(result))
print(cnt)

209715
79578
